name: Docker Image CI
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_PASSWORD }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push the Docker image
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-django:latest .
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-django:latest